services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news_app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    command: sh -lc "composer install --no-interaction --prefer-dist && apache2-foreground"
    environment:
      APP_ENV: dev
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: newsdb
      DB_USER: newsuser
      DB_PASSWORD: newspass
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: news_db
    restart: unless-stopped
    command: ["postgres", "-c", "hba_file=/etc/postgresql/pg_hba.conf"]
    environment:
      POSTGRES_DB: newsdb
      POSTGRES_USER: newsuser
      POSTGRES_PASSWORD: newspass
      POSTGRES_INITDB_ARGS: "-c password_encryption=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./base_donnee:/docker-entrypoint-initdb.d
      - ./postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U newsuser -d newsdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
